### ISSUE TITLE
Building platform for website

### ISSUE THREAD

**Issue by ohpeacock** [blkops/blkops.github.io#1]
Maybe we could use [Jekyll](http://jekyllrb.com/)? Doesn't seem like it'd be too difficult to set up and it would alleviate some of the more difficult design elements (ie. setting up headers and footers). Also apparently well suited for Github Pages: https://help.github.com/articles/using-jekyll-with-pages/

**Comment by jalcine** [comment]
Good idea! That's initially the route I was going but I sat on it for too long.

**Comment by jalcine** [comment]
The only thing now is just having a decent design for the site.

**Comment by miql** [comment]
Glad I'll finally get a chance to try Jekyll!

**Comment by JarettRoman** [comment]
I've used it before. It's pretty convenient.

I couldn't set up a theme though.

Date: Fri, 30 Jan 2015 15:21:50 -0800

**Comment by ohpeacock** [comment]
I've tried it once a few semesters ago. I only wrote a couple of class blog posts though; the site was already set up. It'd be great to work with it again :smile:

**Comment by jalcine** [comment]
Smooth, so we can actually get that (the core guts of the pages) written out whilst we have the design worked on. Each one can live in a separate branch until we merge it back into `gh-pages` :dizzy:

**Comment by bornsky** [comment]
I'm new to jekyll and github but I know enough that I can get around pretty good. I would love to help as little as I can. If I make a mistake somewhere please let me know

**Comment by jalcine** [comment]
@bornsky No problem, man. We're all here to help.

**Comment by ohpeacock** [comment]
It'll be great to have you @bornsky!

**Comment by jalcine** [comment]
We ended up using Jekyll :smile:!
Next steps would be working on the design of the site and seeing where we'd go from there.

**Comment by bornsky** [comment]
No shade to the creator but guess we can improve on the logo a bit

**Comment by jalcine** [comment]
The logo of the organization? Sure, propose one!
